### ISSUE TITLE
interstates comunication

### ISSUE THREAD

**Issue by sonoro1234** [ColonelThirtyTwo/luajit-async#1]
Simple, small and smart is your solution as it is your GLWF binding (which I have used alot)

I have added a "init" argument which is a function to be executed once to make some requires and other initialization stuff for the callbacks.

Threads are only for windows but I see you have LuaJIT-Threads (which has a small compiled file) Shouldn't both projects be merged? 

The only thing I am missisng is interstates comunication (which can be solved with socket or zmq) but I am curious about what you mean with:
"The only way to share information between the main Lua state and the callback is by a
 userdata pointer in the callback function, which you will need to synchronize yourself."

could you provide an example? (without syncronization)

Thanks
victor bombi

**Comment by ColonelThirtyTwo** [comment]
The wording isn't very good. When I said "userdata pointer", I meant a value that is opaque to luajit-async and only used by your code, not a Lua userdata object. Usually, this means a cdata object, which can be accessed and modified by both the main thread and the spawned thread.

``` lua
local shared_data = ffi.new("struct { int foo; }")
local thread = Thread(function(data)
    -- In here, data is a void* pointer to shared_data...
    print(ffi.cast("struct { int foo; }", data).foo)
end, shared_data) -- ...because we passed it in here.
```

LuaJIT-Threads is more limited library; it requires some helper C code which isn't actually needed, and can only be used for making threads. Some other C libraries such as PortAudio, however, need to be passed a function pointer that the library calls from a different thread. Since LuaJIT-Threads was inadequate for that purpose, I made luajit-async as a more general solution, but since I don't need it for any of my other projects yet, I'm not actively working on either library.
